BEGIN TRANSACTION;

DROP TABLE IF EXISTS Tags;
DROP TABLE IF EXISTS OutboundItems;
DROP TABLE IF EXISTS Container;
DROP TABLE IF EXISTS ContainerTypes;
DROP TABLE IF EXISTS WeightRecord;
DROP TABLE IF EXISTS Outbound;
DROP TABLE IF EXISTS Inbound;

COMMIT;